name: Build Thunder on Linux

on:
  push:
    # branches: ["master"]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'ReleaseNotes/**'
  pull_request:
    branches: ["master"]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'ReleaseNotes/**'

jobs:
  Thunder:
    uses: VeithMetro/Thunder/.github/workflows/Linux build template.yml@development/actions

  ThunderInterfaces:
    needs: Thunder
    uses: VeithMetro/ThunderInterfaces/.github/workflows/Linux build template.yml@development/actions

  ThunderLibraries:
    needs: Thunder
    uses: VeithMetro/ThunderLibraries/.github/workflows/Linux build template.yml@development/actions

  ThunderClientLibraries:
    needs: ThunderInterfaces
    uses: VeithMetro/ThunderClientLibraries/.github/workflows/Linux build template.yml@development/actions

  ThunderNanoServices:
    needs: ThunderInterfaces
    uses: VeithMetro/ThunderNanoServices/.github/workflows/Linux build template.yml@development/actions

  ThunderNanoServicesRDK:
    needs: ThunderInterfaces
    uses: VeithMetro/ThunderNanoServicesRDK/.github/workflows/Linux build template.yml@development/actions
