name: Build Thunder on Linux

# TRY TO REVERT SOME TESTS THAT FAILED BEFORE
# CHANGE TO MASTER
on:
  push:
    branches: ["development/actions-tests"]
  pull_request:
    branches: ["master"]
  workflow_call:
 
jobs:
  Thunder:
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        build_type: [Debug, Release, MinSizeRel]

# CHANGE TO RDKCENTRAL
# CHANGE TO MASTER
    name: Build type - ${{matrix.build_type}}
    steps:
    - name: Checkout Thunder
      uses: actions/checkout@v3
      with:
        path: Thunder
        repository: VeithMetro/Thunder
        ref: development/actions-tests

    - name: Checkout ThunderTools
      uses: actions/checkout@v3
      with:
        path: ThunderTools
        repository: rdkcentral/ThunderTools

# TRY WITHOUT libcurl4-openssl-dev
    - name: Install necessary packages
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 10
        command: |
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          sudo apt-get update
          sudo apt install python3-pip
          pip install jsonref
          sudo apt install build-essential cmake ninja-build libusb-1.0-0-dev zlib1g-dev libssl-dev libgtest-dev
        
    - name: Install generators
      run: |
        cmake -G Ninja -S ThunderTools -B ${{matrix.build_type}}/build/ThunderTools \
        -DCMAKE_INSTALL_PREFIX=${{matrix.build_type}}/install/usr
        cmake --build ${{matrix.build_type}}/build/ThunderTools --target install
        
    - name: Build Thunder
      run: |
        cmake -G Ninja -S Thunder -B ${{matrix.build_type}}/build/Thunder \
        -DBINDING="127.0.0.1" \
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
        -DCMAKE_INSTALL_PREFIX="${{matrix.build_type}}/install/usr" \
        -DCMAKE_MODULE_PATH="${PWD}/${{matrix.build_type}}/install/usr/include/WPEFramework/Modules" \
        -DDATA_PATH="${PWD}/${{matrix.build_type}}/install/usr/share/WPEFramework" \
        -DPERSISTENT_PATH="${PWD}/${{matrix.build_type}}/install/var/wpeframework" \
        -DPORT="55555" \
        -DPROXYSTUB_PATH="${PWD}/${{matrix.build_type}}/install/usr/lib/wpeframework/proxystubs" \
        -DSYSTEM_PATH="${PWD}/${{matrix.build_type}}/install/usr/lib/wpeframework/plugins" \
        -DVOLATILE_PATH="tmp" \
        -DBUILD_TESTS=ON
        cmake --build ${{matrix.build_type}}/build/Thunder --target install
    
    - name: Run unit tests
      run: >
        PATH=${{github.workspace}}/${{matrix.build_type}}/install/usr/bin:${PATH}
        LD_LIBRARY_PATH=${{github.workspace}}/${{matrix.build_type}}/install/usr/lib:${LD_LIBRARY_PATH}
        WPEFramework_test_core
    
    - name: Tar files
      run: tar -czvf ${{matrix.build_type}}.tar.gz ${{matrix.build_type}}
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Thunder-${{matrix.build_type}}-artifact
        path: ${{matrix.build_type}}.tar.gz
