name: Linux build template

on:
  workflow_call:

jobs:
  Thunder:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release, MinSizeRel]
        shared_libs: [ON, OFF]
        architecture: [32, 64]

    name: Build type - ${{matrix.shared_libs == 'OFF' && 'Static ' || ''}}${{matrix.build_type}}${{matrix.architecture == '32' && ' x86' || ''}}
    steps:
# --------- Installing packages ---------
    - name: Install necessary packages
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 10
        command: |
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          echo "deb http://archive.ubuntu.com/ubuntu/ jammy main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb http://archive.ubuntu.com/ubuntu/ jammy-updates main universe restricted multiverse" | sudo tee -a /etc/apt/sources.list
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt install python3-pip build-essential cmake ninja-build libusb-1.0-0-dev zlib1g-dev zlib1g-dev:i386 libssl-dev gcc-11-multilib g++-11-multilib
          sudo pip install jsonref

# ----- Checkout & DependsOn regex -----
# --------- Thunder ----------
    - name: Checkout Thunder - default
      if: ${{ !contains(github.event.pull_request.body, '[DependsOn=Thunder:') }}
      uses: actions/checkout@v4
      with:
        path: Thunder
        repository: rdkcentral/Thunder

    - name: Regex Thunder
      if: contains(github.event.pull_request.body, '[DependsOn=Thunder:')
      id: thunder
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '(?<=\[DependsOn=Thunder:).*(?=\])'
        regex_flags: 'gim'
        search_string: ${{github.event.pull_request.body}}

    - name: Checkout Thunder - ${{steps.thunder.outputs.first_match}}
      if: contains(github.event.pull_request.body, '[DependsOn=Thunder:')
      uses: actions/checkout@v4
      with:
        path: Thunder
        repository: rdkcentral/Thunder
        ref: ${{steps.thunder.outputs.first_match}}

# ------- ThunderTools -------
    - name: Checkout ThunderTools - default
      if: ${{ !contains(github.event.pull_request.body, '[DependsOn=ThunderTools:') }}
      uses: actions/checkout@v4
      with:
        path: ThunderTools
        repository: rdkcentral/ThunderTools

    - name: Regex ThunderTools
      if: contains(github.event.pull_request.body, '[DependsOn=ThunderTools:')
      id: tools
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '(?<=\[DependsOn=ThunderTools:).*(?=\])'
        regex_flags: 'gim'
        search_string: ${{github.event.pull_request.body}}

    - name: Checkout ThunderTools - ${{steps.tools.outputs.first_match}}
      if: contains(github.event.pull_request.body, '[DependsOn=ThunderTools:')
      uses: actions/checkout@v4
      with:
        path: ThunderTools
        repository: rdkcentral/ThunderTools
        ref: ${{steps.tools.outputs.first_match}}

# ----- Installing generators & Options regex -----
    - name: Install generators
      run: |
        cmake -G Ninja -S ThunderTools -B ${{matrix.build_type}}/build/ThunderTools \
        -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Werror -m${{matrix.architecture}}" \
        -DCMAKE_C_FLAGS="-Wall -Wextra -Wpedantic -Werror -m${{matrix.architecture}}" \
        -DCMAKE_INSTALL_PREFIX=${{matrix.build_type}}/install/usr
        cmake --build ${{matrix.build_type}}/build/ThunderTools --target install

    - name: Regex Thunder
      if: contains(github.event.pull_request.body, '[Options:')
      id: regexthunder
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '(?<=\[Options:).*(?=\])'
        regex_flags: 'gim'
        search_string: ${{github.event.pull_request.body}}

# ----- Building & uploading artifacts -----
    - name: Build Thunder
      run: |
        cmake -G Ninja -S Thunder -B ${{matrix.build_type}}/build/Thunder \
        -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Werror -m${{matrix.architecture}}" \
        -DCMAKE_C_FLAGS="-Wall -Wextra -Wpedantic -Werror -m${{matrix.architecture}}" \
        -DBUILD_SHARED_LIBS=${{matrix.shared_libs}} \
        -DBINDING="127.0.0.1" \
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
        -DCMAKE_INSTALL_PREFIX="${{matrix.build_type}}/install/usr" \
        -DCMAKE_MODULE_PATH="${PWD}/${{matrix.build_type}}/install/usr/include/WPEFramework/Modules" \
        -DDATA_PATH="${PWD}/${{matrix.build_type}}/install/usr/share/WPEFramework" \
        -DPERSISTENT_PATH="${PWD}/${{matrix.build_type}}/install/var/wpeframework" \
        -DPORT="55555" \
        -DPROXYSTUB_PATH="${PWD}/${{matrix.build_type}}/install/usr/lib/wpeframework/proxystubs" \
        -DSYSTEM_PATH="${PWD}/${{matrix.build_type}}/install/usr/lib/wpeframework/plugins" \
        -DVOLATILE_PATH="tmp" \
        -DLOCALTRACER=ON \
        -DWARNING_REPORTING=ON \
        -DPROCESSCONTAINERS=ON \
        -DPROCESSCONTAINERS_RUNC=ON \
        ${{steps.regexthunder.outputs.first_match}}
        cmake --build ${{matrix.build_type}}/build/Thunder --target install

    - name: Tar files
      if: matrix.shared_libs == 'ON'
      run: tar -czvf ${{matrix.build_type}}${{matrix.architecture == '32' && '_x86' || ''}}.tar.gz ${{matrix.build_type}}

    - name: Upload
      if: matrix.shared_libs == 'ON'
      uses: actions/upload-artifact@v4
      with:
        name: Thunder-${{matrix.build_type}}${{matrix.architecture == '32' && '_x86' || ''}}-artifact
        path: ${{matrix.build_type}}${{matrix.architecture == '32' && '_x86' || ''}}.tar.gz
